# Generated by Django 3.0.2 on 2020-02-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200205_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='special_toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='topping',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopping_cart_item',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_in_order', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='orders.Category'),
        ),
    ]
