# Generated by Django 3.0.2 on 2020-02-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200207_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_cart_item',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='special_toppings',
            field=models.ManyToManyField(blank=True, related_name='items', to='orders.Topping'),
        ),
    ]
