# Generated by Django 3.0.2 on 2020-02-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200208_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=64),
        ),
        migrations.RemoveField(
            model_name='topping',
            name='category',
        ),
        migrations.AddField(
            model_name='topping',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='toppings', to='orders.Category'),
        ),
    ]
